<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <ProjectReference Include="..\..\apps\AtProto.FirehoseProbe\AtProto.FirehoseProbe.csproj" />
    <ProjectReference Include="..\..\apps\AtProto.StatusSeeder\AtProto.StatusSeeder.csproj" />
    <ProjectReference Include="..\..\services\AtProto.AppView\AtProto.AppView.csproj" />
    <ProjectReference Include="..\..\services\AtProto.Pds\AtProto.Pds.csproj" />
    <ProjectReference Include="..\..\services\AtProto.Relay\AtProto.Relay.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>67933982-b5a6-4bb8-b444-ef5cb536f164</UserSecretsId>
  </PropertyGroup>

</Project>
