<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\services\AtProto.Pds\AtProto.Pds.csproj" />
    <ProjectReference Include="..\..\src\services\AtProto.AppView\AtProto.AppView.csproj" />
    <ProjectReference Include="..\..\src\services\AtProto.Relay\AtProto.Relay.csproj" />
    <ProjectReference Include="..\..\src\core\AtProto.Firehose\AtProto.Firehose.csproj" />
    <ProjectReference Include="..\..\src\core\AtProto.Car\AtProto.Car.csproj" />
    <ProjectReference Include="..\..\src\core\AtProto.Repo\AtProto.Repo.csproj" />
    <ProjectReference Include="..\..\src\core\AtProto.Crypto\AtProto.Crypto.csproj" />
    <ProjectReference Include="..\..\src\core\AtProto.Cbor\AtProto.Cbor.csproj" />
  </ItemGroup>

</Project>
