<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\core\AtProto.Firehose\AtProto.Firehose.csproj" />
    <ProjectReference Include="..\..\core\AtProto.Car\AtProto.Car.csproj" />
    <ProjectReference Include="..\..\core\AtProto.Cbor\AtProto.Cbor.csproj" />
    <ProjectReference Include="..\..\core\AtProto.Identity\AtProto.Identity.csproj" />
    <ProjectReference Include="..\..\core\AtProto.Lexicon\AtProto.Lexicon.csproj" />
    <ProjectReference Include="..\..\aspire\AtProto.ServiceDefaults\AtProto.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
</Project>
