<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="AtProto.Firehose" />
    <PackageReference Include="AtProto.Car" />
    <PackageReference Include="AtProto.Cbor" />
    <PackageReference Include="AtProto.Identity" />
    <PackageReference Include="AtProto.Lexicon" />
    <ProjectReference Include="..\..\aspire\AtProto.ServiceDefaults\AtProto.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
</Project>
