using System.Globalization;
using System.Text;
using System.Text.Json;

namespace AtProto.Lexicon.CodeGen;

/// <summary>Generates C# records from AT Protocol lexicon record definitions.</summary>
public static class LexiconCodeGenerator
{
    public static string Generate(string lexiconJson, LexiconCodeGeneratorOptions? options = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(lexiconJson);
        options ??= new LexiconCodeGeneratorOptions();

        using var document = JsonDocument.Parse(lexiconJson);
        var root = document.RootElement;
        var nsid = root.GetRequiredString("id");
        var main = root.GetProperty("defs").GetProperty("main");

        if (!main.TryGetProperty("type", out var typeElement) || typeElement.GetString() != "record")
        {
            throw new NotSupportedException("Only defs.main records are supported.");
        }

        var record = main.GetProperty("record");
        if (!record.TryGetProperty("type", out var recordTypeElement) || recordTypeElement.GetString() != "object")
        {
            throw new NotSupportedException("Only object record schemas are supported.");
        }

        var properties = record.GetProperty("properties");
        var @namespace = options.Namespace ?? DeriveNamespace(nsid);
        var typeName = options.TypeName ?? DeriveTypeName(nsid);
        if (options.TypeName is null && properties.EnumerateObject().Any(property => string.Equals(ToPascalCase(property.Name), typeName, StringComparison.Ordinal)))
        {
            typeName += "Record";
        }

        var required = ReadRequiredProperties(record);
        var description = main.TryGetProperty("description", out var descriptionElement)
            ? descriptionElement.GetString()
            : null;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Namespace convention: NSID segments before the final segment become PascalCase namespace segments; the final segment becomes the record type name.");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine();
        builder.AppendLine($"namespace {@namespace};");
        builder.AppendLine();

        if (!string.IsNullOrWhiteSpace(description))
        {
            AppendXmlSummary(builder, description!);
        }

        builder.AppendLine($"public sealed record class {typeName}");
        builder.AppendLine("{");
        builder.AppendLine($"    public const string Nsid = \"{EscapeStringLiteral(nsid)}\";");
        builder.AppendLine();
        builder.AppendLine("    [JsonPropertyName(\"$type\")]");
        builder.AppendLine("    public string Type { get; init; } = Nsid;");

        foreach (var property in properties.EnumerateObject())
        {
            var propertyName = property.Name;
            var csharpName = ToPascalCase(propertyName);
            var isRequired = required.Contains(propertyName);
            var csharpType = MapType(property.Value, isRequired);
            var propertyDescription = property.Value.TryGetProperty("description", out var propertyDescriptionElement)
                ? propertyDescriptionElement.GetString()
                : null;

            builder.AppendLine();
            if (!string.IsNullOrWhiteSpace(propertyDescription))
            {
                AppendXmlSummary(builder, propertyDescription!, "    ");
            }

            builder.AppendLine($"    [JsonPropertyName(\"{EscapeStringLiteral(propertyName)}\")]");
            var requiredKeyword = IsNullableType(csharpType) ? string.Empty : "required ";
            builder.AppendLine($"    public {requiredKeyword}{csharpType} {csharpName} {{ get; init; }}");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static HashSet<string> ReadRequiredProperties(JsonElement record)
    {
        if (!record.TryGetProperty("required", out var requiredElement) || requiredElement.ValueKind != JsonValueKind.Array)
        {
            return [];
        }

        return requiredElement.EnumerateArray()
            .Select(static item => item.GetString())
            .Where(static item => !string.IsNullOrWhiteSpace(item))
            .Select(static item => item!)
            .ToHashSet(StringComparer.Ordinal);
    }

    private static string MapType(JsonElement schema, bool isRequired)
    {
        var lexiconType = schema.GetRequiredString("type");
        var type = lexiconType switch
        {
            "string" when schema.TryGetProperty("format", out var format) && format.GetString() == "datetime" => "DateTimeOffset",
            "string" => "string",
            "integer" => MapIntegerType(schema),
            "boolean" => "bool",
            "array" => $"IReadOnlyList<{MapArrayItemType(schema)}>",
            "blob" or "ref" or "union" => "object",
            _ => "object"
        };

        return isRequired ? type : ToNullableType(type);
    }

    private static string MapArrayItemType(JsonElement schema)
    {
        if (!schema.TryGetProperty("items", out var items) || items.ValueKind != JsonValueKind.Object)
        {
            return "object";
        }

        return MapType(items, isRequired: true);
    }

    private static string MapIntegerType(JsonElement schema)
    {
        var minimumFits = !schema.TryGetProperty("minimum", out var minimum) || minimum.GetInt64() >= int.MinValue;
        var maximumFits = !schema.TryGetProperty("maximum", out var maximum) || maximum.GetInt64() <= int.MaxValue;
        return minimumFits && maximumFits ? "int" : "long";
    }

    private static string ToNullableType(string type) => type == "object" || type == "string" || type.StartsWith("IReadOnlyList<", StringComparison.Ordinal)
        ? type + "?"
        : type + "?";

    private static bool IsNullableType(string type) => type.EndsWith("?", StringComparison.Ordinal);

    private static string DeriveNamespace(string nsid)
    {
        var segments = nsid.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (segments.Length <= 1)
        {
            return "Lexicons";
        }

        return string.Join('.', segments.Take(segments.Length - 1).Select(ToPascalCase));
    }

    private static string DeriveTypeName(string nsid)
    {
        var lastSegment = nsid.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).LastOrDefault();
        return string.IsNullOrWhiteSpace(lastSegment) ? "LexiconRecord" : ToPascalCase(lastSegment);
    }

    private static string ToPascalCase(string value)
    {
        var builder = new StringBuilder();
        var capitalizeNext = true;

        foreach (var character in value)
        {
            if (!char.IsLetterOrDigit(character))
            {
                capitalizeNext = true;
                continue;
            }

            if (builder.Length == 0 && char.IsDigit(character))
            {
                builder.Append('_');
            }

            builder.Append(capitalizeNext ? char.ToUpper(character, CultureInfo.InvariantCulture) : character);
            capitalizeNext = false;
        }

        return builder.Length == 0 ? "Value" : builder.ToString();
    }

    private static void AppendXmlSummary(StringBuilder builder, string summary, string indent = "")
    {
        builder.AppendLine($"{indent}/// <summary>");
        builder.AppendLine($"{indent}/// {EscapeXml(summary)}");
        builder.AppendLine($"{indent}/// </summary>");
    }

    private static string EscapeXml(string value) => value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal);

    private static string EscapeStringLiteral(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}

internal static class JsonElementExtensions
{
    public static string GetRequiredString(this JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var property) || property.ValueKind != JsonValueKind.String)
        {
            throw new JsonException($"Expected string property '{propertyName}'.");
        }

        return property.GetString()!;
    }
}
